::Const.Strings.JccPerchtNames <- [
	"Beelzebub",
	"Corvus",
	"Adramahlihk",
	"Duma",
	"Dagon",
	"Molag",
	"Barbatos",
	"Astaroth",
	"Nergal",
	"Ereshkigal",
	"Anankos",
	"Baphomet",
	"Alastor",
	"Gaucher",
	"Cambion",
	"Mammon",
	"Mephistopheles",
	"Grima",
	"Dagoth",
	"Belial",
	"Azazel",
	"Pan",
	"Samail",
	"Rubezahl",
	"Gil\'dan",
	"Kil\'jaeden",
	"Moloch",
	"Krampus",
	"Vader Johan"
];
::Const.Strings.JccPerchtaNames <- [
	"Lilith",
	"Pandora",
	"Justice",
	"Brunhilde"
];
::Const.Strings.JccPerchtaTitles <- [
	"the Harrier",
	"Bal",
	"the Great Horned One",
	"the Child Snatcher",
	"of the Black Sabbath",
	"the Maneater",
	"the Impaler",
	"Ash-Spitter",
	"Ur",
	"the Black",
	"Coal-Eyes",
	"the Raucous",
	"from Below",
	"the Black Bellows",
	"the Peeler",
	"the Anathema",
	"the King in Yellow",
	"Sack-Stuffer",
	"Gore-Spiller",
	"of the Underworld",
	"the Boogeyman",
	"of the Dark",
	"the Bump in the Night",
	"the Helltaker"
];
::Const.Strings.JccPerchtTitles <- [
	"the Harrier",
	"Bal",
	"the Great Horned One",
	"the Child Snatcher",
	"of the Black Sabbath",
	"the Maneater",
	"the Impaler",
	"Ash-Spitter",
	"Ur",
	"the Black",
	"Coal-Eyes",
	"the Raucous",
	"from Below",
	"the Black Bellows",
	"the Peeler",
	"the Anathema",
	"the King in Yellow",
	"the Old Man of the Mountain",
	"Sack-Stuffer",
	"Gore-Spiller",
	"of the Underworld",
	"the Boogeyman",
	"of the Dark",
	"the Bump in the Night",
	"the Helltaker"
];
::Const.World.LocationNames.PerchtClearing <- [
	"Fortified Den",
	"Hell\'s Gate",
	"Eerie Clearing",
	"Gathering Stones",
	"Herdstones",
	"Spirit\'s Well",
	"Summoning Stones",
	"Bone-Strewn Hellhole",
	"Field of Delirium",
	"Ill-Omened Clearing",
	"Hellspawn\'s Den",
	"Sacrifice Rock",
	"Bone-Strewn Clearing",
	"Sealing Stones",
	"Pale Glade",
	"Silent Copse",
	"Wretched Clearing",
	"Abandoned Hunter\'s Camp",
	"Hunter\'s End",
	"Percht\'s Glade",
	"Uncharted Clearing",
	"Haunted Moor",
	"Den of Coal",
	"Den of Sulfur",
	"Huntsman\'s Copse",
	"Huntsman\'s End",
	"Gateless Gate"
];
::Const.World.LocationNames.PerchtCastle <- [
	"Child-Eater Hall",
	"Hall of Hell",
	"Greenbeard\'s Walls",
	"Hall of the Mountain King"
];
::Const.Strings.JccSlimeNames <- [
	"Bodysnatcher",
	"Slimer",
	"Roteater",
	"Scumsucker",
	"Manmelter",
	"Maneater",
	"Manbiter",
	"Skullstripper",
	"The Thing",
	"The Blob",
	"Rimuru",
	"The Pulse",
	"Nameless Sludge",
	"Putrid Mucus",
	"The Red Guck",
	"Glopping Biomass",
	"Slimed Squire",
];
::Const.Strings.JccBeastslayerNames <- [
	"Geralt",
	"Siegfried",
	"Valter",
	"Vesemir",
	"Letho",
	"Dwayne",
	"Bazuso",
	"Werner",
	"Caellach",
	"Mordred",
	"Esparr",
	"Hektor",
	"Gotz",
	"Uther",
	"Orion",
	"Chulainn",
	"Lobo"
];
::Const.Strings.JccBeastslayerTitles <- [
	"the Witcher",
	"LaFontant"
	"the Dragonslayer",
	"the Wurmslayer",
	"the Moonstone",
	"the Schrat-Splitter",
	"the Unmaker",
	"the Slayer",
	"the Verminator",
	"the Bear-Wrestler",
	"Spider-Stomper",
	"Wolfsbane",
	"Hagsbane",
	"Hag-Hacker",
	"Woodstalker",
	"of Wurmwald",
	"the Chicken",
	"the Robin",
	"the Tiger-Eye"
];

::Const.Strings.JccDjinnNames <- [
	"Hatschi Bratschi",
	"Al-Madhab",
	"Al-Abyad",
	"Al-Ahmar",
	"Barqan",
	"Samhures",
	"Zawba\'ah",
	"Maymun",
	"Jaffar"
];

::Const.Strings.JccDjinnTitles <- [
	"the Soot-Spitter",
	"the Wishmaster",
	"the Deceiver",
	"Plaguebringer",
	"the Blue Blaze",
	"the Golden One",
	"the White One",
	"the Red One",
	"Two Thunders",
	"the Prosperous",
	"of the One Thousand and One Nights",
	"the Ifrit",
	"Shaitan"
];

::Const.World.LocationNames.DjinnMirage <- [
	"Red Sands",
	"Mirror\'s Edge",
	"Spirit Oasis",
	"Djinn\'s Communion",
	"Refracted Oasis",
	"Hope\'s End",
	"Spirit Waters",
	"Bloodied Sands"
];

::Const.World.LocationNames.DjinnGrotto <- [
	"Deceiver\'s Grotto",
	"Eternal Reward"
];