::Const.Strings.JccPerchtNames <- [
	"Beelzebub",
	"Corvus",
	"Adramahlihk",
	"Duma",
	"Dagon",
	"Molag",
	"Barbatos",
	"Astaroth",
	"Nergal",
	"Ereshkigal",
	"Anankos",
	"Baphomet",
	"Alastor",
	"Gaucher",
	"Cambion",
	"Mammon",
	"Mephistopheles",
	"Grima",
	"Dagoth",
	"Belial",
	"Azazel",
	"Pan",
	"Samail",
	"Rubezahl",
	"Gil\'dan",
	"Kil\'jaeden",
	"Moloch",
	"Krampus"
];
::Const.Strings.JccPerchtTitles <- [
	"the Harrier",
	"Bal",
	"the Great Horned One",
	"the Child Snatcher",
	"of the Black Sabbath",
	"the Maneater",
	"the Impaler",
	"Ash-Spitter",
	"Ur",
	"the Black",
	"Coal-Eyes",
	"the Raucous",
	"from Below",
	"the Black Bellows",
	"the Peeler",
	"the Anathema",
	"the King in Yellow",
	"the Old Man of the Mountain",
	"Sack-Stuffer",
	"Gore-Spiller",
	"of the Underworld",
	"the Boogeyman",
	"of the Dark",
	"the Bump in the Night"
];
::Const.World.LocationNames.PerchtClearing <- [
	"Fortified Den",
	"Hell\'s Gate",
	"Eerie Clearing",
	"Gathering Stones",
	"Herdstones",
	"Spirit\'s Well",
	"Summoning Stones",
	"Bone-Strewn Hellhole",
	"Field of Delirium",
	"Ill-Omened Clearing",
	"Hellspawn\'s Den",
	"Sacrifice Rock",
	"Bone-Strewn Clearing",
	"Sealing Stones",
	"Pale Glade",
	"Silent Copse",
	"Wretched Clearing",
	"Abandoned Hunter\'s Camp",
	"Hunter\'s End",
	"Percht\'s Glade",
	"Uncharted Clearing",
	"Haunted Moor",
	"Den of Coal",
	"Den of Sulfur",
	"Huntsman\'s Copse",
	"Huntsman\'s End"
];
::Const.World.LocationNames.PerchtCastle <- [
	"Child-Eater Hall",
	"Hall of Hell",
	"Greenbeard\'s Walls"
];
::Const.Strings.JccSlimeNames <- [
	"Bodysnatcher",
	"Slimer",
	"Roteater",
	"Scumsucker",
	"Manmelter",
	"Maneater",
	"Manbiter",
	"Skullstripper",
	"The Thing",
	"The Blob"
];